version: "3"
services:
  app:
    container_name: "metal-app"
    build:
      context: ./app
      dockerfile: ./Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000

  e2e:
    container_name: "metal-e2e"
    image: mcr.microsoft.com/playwright:v1.10.0-focal
    working_dir: /e2e
    tty: true
    volumes:
      - ./e2e:/e2e
      - node_modules:/e2e/node_modules

volumes:
  node_modules:
    driver: "local"
