version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000

volumes:
  node_modules:
    driver: 'local'